# Generated by Django 5.1.4 on 2024-12-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_task_lists', to='tasks.user'),
        ),
    ]
