# Generated by Django 5.1.4 on 2024-12-16 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskdo'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdo',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskdo',
            name='task_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.tasklist'),
        ),
        migrations.AlterField(
            model_name='taskdo',
            name='is_completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
