# Generated by Django 5.1.4 on 2024-12-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskdo_due_date_taskdo_task_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
